// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Bootique Integration with Logback

As mentioned in Bootique http://bootique.io/docs/0/bootique-docs/index.html#logging[general documentation on logging],
standard modules rely on SLF4J loggers that can be easily bridged to various advanced logging frameworks. Same
maximally neutral logging approach is reasonable to apply in the user modules as well.

https://github.com/bootique/bootique-logback[`bootique-logback`] is a "drag-and-drop" module integrating Bootique
logging with http://logback.qos.ch/[Logback logging framework]. Just like any other module, `bootique-logback` can be
enabled by simply adding it to the `pom.xml` dependencies, assuming `autoLoadModules()` is in effect:

.Maven
[%collapsible%open]
====
[source,xml]
----
<dependency>
    <groupId>io.bootique.logback</groupId>
    <artifactId>bootique-logback</artifactId>
</dependency>
----
====

.Gradle
[%collapsible]
====
[source,groovy]
----
{
  implementation: 'io.bootique.logback:bootique-logback'
}
----
====

Without further configuration it would log everything to console using INFO level. Configuration can be provided via
YAML, as shown in the <<_configuration_reference,Configuration Reference>> section. Configuration options include per
class and package log levels configuration, a choice of appenders, etc.
