// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

== Configuration Reference

=== log

[source,yaml]
----
log:
  level: warn
  appenderRefs:
    - test
  loggers:
    com.foo:
      level: debug
      appenderRefs:
        - test
    com.example:
      level: debug
  appenders:
    - type: file
      name: test
      file: target/logback/testRun_Debug.log
      filters:
        - type: threshold
          level: info
      layout:
        type: pattern
        logFormat: '%c{20}: %m%n'
----
"log" is a root element of the Logback configuration and is bound to a
https://github.com/bootique/bootique-logback/blob/master/bootique-logback/src/main/java/io/bootique/logback/LogbackContextFactory.java[`LogbackContextFactory`]
object. It supports the following properties:

."log" Element Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`appenders`
|console appender
|A list of appenders to output logs to. See below.

|`appenderRefs`
|none
|A list of references to appenders. If it's added to child logger only, then the
child logger will write logs with this named appender. If the appender added
to the root logger, or to both root and child loggers, or none, the appender
will be attached to root logger only.

|`level`
|`info`
|A default logging level. Can be overridden per logger.

|`loggers`
|none
|A map of logger factories by logger name. Logger name is a package name (applied recursively) or class name. See below.

|`useLogbackConfig`
|`false`
|If true, all other logback settings are ignored and the user is expected to provide its own config file per
http://logback.qos.ch/manual/configuration.html[Logback documentation]. This is only needed for a few advanced options
not directly available via Bootique config.
|===

=== log.appenders

[source,yaml]
----
log:
  appenders:
    - type: file
      name: test
      file: /var/log/myapp.log
      layout:
        type: json
        timestampFormat: "yyyy-MM-dd HH:mm"
    - type: console
      layout:
        type: pattern
        logFormat: '%c{20}: %m%n'
----
Lists appenders to sends the logs to. If the list is empty, console appender is used with default settings. Currently
available appenders are "console" and "file":

."console" Appender Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`logFormat`
|`%-5p [%d{ISO8601,UTC}] %thread %c{20}: %m%n%rEx`
|A format of the log lines. See Logback http://logback.qos.ch/manual/layouts.html#ClassicPatternLayout[PatternLayout]
for details.
Moved in the layout properties.

|`target`
|`stdout`
|Whether to log to standard output or standard error. Possible values are `stdout` and `stderr`

|`filters`
|none
|A collection of filters to use with this appender

|`layout`
|pattern
|Layout config for this appender. Possible values are `pattern` and `json`. Examples given <<log.appenders.layout,below>>
|===



."file" Appender Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`logFormat`
|`%-5p [%d{ISO8601,UTC}] %thread %c{20}: %m%n%rEx`
|A format of the log lines. See Logback http://logback.qos.ch/manual/layouts.html#ClassicPatternLayout[PatternLayout]
for details.
Moved in the layout properties.

|`name`
|none
|The name of the appender. If it has a name it could be added to the loggers by that name. If it has no name it will
be automatically added to the root logger.

|`file`
|none
|A name of a file to send the log to.

|`append`
|true
|If true, events are appended at the end of an existing file. Otherwise, if append is false, any existing file is
truncated. The append option is set to true by default.

|`rollingPolicy`
|none
|An object that defines a log rotation policy. Examples are given <<log.appenders.rollingPolicy,below>>.

|`filters`
|none
|A collection of filters to use with this appender. See link:#_log_appenders_filters[filters] section.

|`layout`
|pattern
|Layout config for this appender. Possible values are `pattern` and `json`. Examples given <<log.appenders.layout,below>>
|===

There are a few ways log file rotation can be configured for the "file" appender, as defined by the `rollingPolicy`.
Out of the box the following Logback policies are supported:
http://logback.qos.ch/manual/appenders.html#FixedWindowRollingPolicy[`fixedWindow`],
http://logback.qos.ch/manual/appenders.html#TimeBasedRollingPolicy[`time`], `sizeAndTime`.

=== log.appenders.rollingPolicy

==== "fixedWindow" Rolling Policy

[source,yaml]
----
log:
  appenders:
    - type: file
      file: /var/log/myapp.log
      rollingPolicy:
        type: fixedWindow
        fileNamePattern: '/var/log/myapp-%i.log'
        historySize: 5
        fileSize: 20
      layout:
        type: pattern
        logFormat: '%c{20}: %m%n'
----
"fixedWindow" policy rotates the main log file when it reaches a certain size, keeping one or more rotated files.

."fixedWindow" rolling policy Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`fileNamePattern`
|none
|A pattern of rotated file name. Must contain `%i` somewhere in the pattern (replaced by a number during rotation).

|`historySize`
|none (unlimited)
|A max number of rotated files to keep.

|`fileSize`
|none
|Max file size that causes rotation. Expressed in bytes, kilobytes, megabytes or gigabytes by suffixing a numeric
value with KB, MB and respectively GB. For example: 5000000, 5000KB, 5MB and 2GB.
|===

==== "time" Rolling Policy

[source,yaml]
----
log:
  appenders:
    - type: file
      file: /var/log/myapp.log
      logFormat: '%c{20}: %m%n'
      rollingPolicy:
        type: time
        fileNamePattern: '/var/log/myapp-%d{yyyyMMddHHmmss}.log'
      layout:
        type: pattern
----
"time" policy rotates the main log file at a fixed time interval determined by the file name pattern.

."time" rolling policy Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`fileNamePattern`
|none
|A pattern of rotated file name. Its value should consist of the name of the file, plus a suitably placed %d
conversion specifier. The %d conversion specifier may contain a date-and-time pattern as specified by the
`java.text.SimpleDateFormat` class. If the date-and-time pattern is omitted, then the default pattern `yyyy-MM-dd`
is assumed. The rollover interval is inferred from the value of the pattern.

|`historySize`
|none (unlimited)
|A max number of rotated files to keep.

|`totalSize`
|none
|Max size of all log files combined. Expressed in bytes, kilobytes, megabytes or gigabytes by suffixing a numeric value
with KB, MB and respectively GB. For example: 5000000, 5000KB, 5MB and 2GB.
|===

==== "sizeAndTime" Rolling Policy

[source,yaml]
----
log:
  appenders:
    - type: file
      file: /var/log/myapp.log
      rollingPolicy:
        type: sizeAndTime
        fileNamePattern: '/var/log/myapp-%d{yyyyMMddHHmmss}.%i.log'
        historySize: 5
        fileSize: 50
        totalSize: 150
      layout:
        type: pattern
        logFormat: '%c{20}: %m%n'
----
"sizeAndTime" policy rotates the main log file either at a fixed time interval determined by the file name pattern or
when the log file reaches a certain size.

."sizeAndTime" rolling policy Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`fileNamePattern`
|none
|A pattern of rotated file name. Its value should consist of the name of the file, plus a suitably placed %d conversion
specifier. The %d conversion specifier may contain a date-and-time pattern as specified by the
`java.text.SimpleDateFormat` class. If the date-and-time pattern is omitted, then the default pattern `yyyy-MM-dd` is
assumed. The rollover interval is inferred from the value of the pattern.

|`historySize`
|none (unlimited)
|A max number of rotated files to keep.

|`totalSize`
|none
|Max size of all log files combined. Expressed in bytes, kilobytes, megabytes or gigabytes by suffixing a numeric value
with KB, MB and respectively GB. For example: 5000000, 5000KB, 5MB and 2GB.

|`fileSize`
|none
|Max file size that causes rotation. Expressed in bytes, kilobytes, megabytes or gigabytes by suffixing a numeric
value with KB, MB and respectively GB. For example: 5000000, 5000KB, 5MB and 2GB.
|===

=== log.appenders.filters

==== "level" Filter

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: file
      file: target/logs/info-only.log
      logFormat: '%c{20}: %m%n'
      filters:
        - type: level
          level: info
          onMatch: accept
          onMismatch: deny
      layout:
        type: pattern
----

`level` filter filters events based on exact level matching.

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`level`
|none
|logging event level to filter

|`onMatch`
|neutral
|action to take on event level match (`accept`, `deny`, `neutral`)

|`onMismatch`
|neutral
|action to take on event level mismatch (`accept`, `deny`, `neutral`)
|===

==== "threshold" Filter

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: console
      filters:
        - type: threshold
          level: warn
----

`threshold` filter filters events below the specified level threshold.
Events with a level below the threshold will be denied.

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`level`
|none
|logging event level to filter
|===

=== log.appenders.layout [[log.appenders.layout]]

==== Layout "pattern"

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: file
      file: target/logs/info-only.log
      layout:
        type: pattern
        logFormat: '%c{20}: %m%n'
----

`pattern` layout configure log massage as plain text.

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`logFormat`
|`%-5p [%d{ISO8601,UTC}] %thread %c{20}: %m%n%rEx`
|A format of the log lines. See Logback http://logback.qos.ch/manual/layouts.html#ClassicPatternLayout[PatternLayout]
for details.
|===

==== Layout "json"

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: file
      file: target/logs/info-only.log
      layout:
        type: json
        timestampFormat: 'yyyy-MM-dd HH:mm:ss'
        prettyPrint: true
----

`json` layout configure log massage as json.

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`timestampFormat`
|`yyyy-MM-dd HH:mm:ss.SSS`
|A format of the timestamp value.

|`prettyPrint`
|`false`
|Option for human-readable output.
|===

==== Layout "html"

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: file
      file: target/logs/info-only.html
      layout:
        type: html
        pattern: %relative%thread%level%logger%msg
----

`html` layout configure log massage as html page. See Logback https://logback.qos.ch/manual/layouts.html#ClassicHTMLLayout[HTMLLayout]

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`pattern`
|`%relative%thread%mdc%level%logger%msg`
|Each specifier found in the pattern will result in a separate column. Likewise a separate column will be generated for each block of literal text found in the pattern, potentially wasting valuable real-estate on your screen. See Logback http://logback.qos.ch/manual/layouts.html#ClassicPatternLayout[PatternLayout]
|===

==== Layout "xml"

[source,yaml]
----
log:
  level: debug
  appenders:
    - type: file
      file: target/logs/info-only.xml
      layout:
        type: xml
        locationInfo: true
        properties: true
----

`xml` layout configure log massage as xml. See Logback https://logback.qos.ch/manual/layouts.html#log4jXMLLayout[XMLLayout]

[cols=3*,options=header]
|===
|Property
|Default
|Description

|`locationInfo`
|`false`
|Setting `locationInfo` to true enables the inclusion of location info (caller data) in the each event.

|`properties`
|`false`
|Setting `properties` to true enables the inclusion of MDC information. Both options are set to false by default.
|===

=== log.loggers

[source,yaml]
----
log:
  loggers:
    com.foo:
      level: debug
    com.example:
      level: debug
----
This is a map of
https://github.com/bootique/bootique-logback/blob/master/bootique-logback/src/main/java/io/bootique/logback/LoggerFactory.java[logger factories]
by logger name. Logger name is either a package name (applied recursively to subpackages and their classes) or a class
name. Each LoggerFactory has the following properties:

.Logger Property Reference
[cols=3*,options=header]
|===
|Property
|Default
|Description

|`level`
|`info`
|Log level for a particular logger. Can be `off`, `error`, `warn`, `info`, `debug`, `trace`, `all`
|===